# ────────────── Input & Touchpad ──────────────
input {
    kb_layout = us
    numlock_by_default = true
    follow_mouse = 0

    sensitivity = 0.0
    accel_profile = flat

    touchpad {
        natural_scroll = true
        tap-to-click = true
        drag_lock = false
        scroll_factor = 1.0
    }
}

gestures {
    workspace_swipe_distance = 300
    workspace_swipe_cancel_ratio = 0.5
}
